/* Mise browser runtime: tiny local renderer + hooks. No external dependencies. */
const Fragment = Symbol("Fragment");
function flatChildren(input,out=[]){for(const child of input){if(Array.isArray(child))flatChildren(child,out);else if(child!==null&&child!==undefined&&child!==false&&child!==true)out.push(child)}return out}
function h(type,props,...children){props=props||{};const all=flatChildren(children);return{type,props:{...props,children:all.length===0?undefined:all.length===1?all[0]:all},key:props.key??null}}
const __hooks=new Map();let __component=null,__hookIndex=0,__used=new Set(),__pendingEffects=[],__scheduled=false,__root=null,__rootVNode=null,__nodes=new Map(),__autoFocus=null;
function depsChanged(a,b){if(!a||!b||a.length!==b.length)return true;for(let i=0;i<a.length;i++)if(!Object.is(a[i],b[i]))return true;return false}
function hookSlot(kind,init){if(!__component)throw new Error(kind+" called outside component");let list=__hooks.get(__component);if(!list){list=[];__hooks.set(__component,list)}const i=__hookIndex++;if(!list[i])list[i]={kind,...init()};return[list[i],i,__component]}
function useState(initial){const [slot,index,path]=hookSlot("state",()=>({value:typeof initial==="function"?initial():initial}));const setter=value=>{const list=__hooks.get(path);if(!list||!list[index])return;const current=list[index].value;const next=typeof value==="function"?value(current):value;list[index].value=next;scheduleRender()};return[slot.value,setter]}
function useRef(initial){const [slot]=hookSlot("ref",()=>({ref:{current:initial}}));return slot.ref}
function useMemo(factory,deps){const [slot]=hookSlot("memo",()=>({deps:undefined,value:undefined,ready:false}));if(!slot.ready||depsChanged(slot.deps,deps)){slot.value=factory();slot.deps=deps;slot.ready=true}return slot.value}
function useEffect(effect,deps){const [slot,index,path]=hookSlot("effect",()=>({deps:undefined,cleanup:null}));if(depsChanged(slot.deps,deps)){__pendingEffects.push({path,index,effect,deps})}}
function scheduleRender(){if(__scheduled)return;__scheduled=true;queueMicrotask(()=>{__scheduled=false;renderRoot()})}
function setStyle(el,obj){if(typeof obj==="string"){el.style.cssText=obj;return}for(const [k,v] of Object.entries(obj||{})){if(k.startsWith("--"))el.style.setProperty(k,String(v));else try{el.style[k]=v==null?"":String(v)}catch{}}}
function svgAttr(name){return({className:"class","strokeWidth":"stroke-width","strokeLinecap":"stroke-linecap","strokeLinejoin":"stroke-linejoin","strokeMiterlimit":"stroke-miterlimit","fillRule":"fill-rule","clipRule":"clip-rule"})[name]||name.replace(/[A-Z]/g,m=>"-"+m.toLowerCase())}
function applyProp(el,name,value,isSvg,tag){if(name==="children"||name==="key"||name==="ref"||value===undefined||value===null)return;if(name==="className"){el.setAttribute("class",String(value));return}if(name==="style"){setStyle(el,value);return}if(name.startsWith("on")&&typeof value==="function"){let ev=name.slice(2).toLowerCase();if(ev==="doubleclick")ev="dblclick";if(ev==="change"){const type=String(el.type||"").toLowerCase();ev=(tag==="select"||type==="file"||type==="checkbox"||type==="radio")?"change":"input"}el.addEventListener(ev,value);return}if(isSvg){el.setAttribute(svgAttr(name),String(value));return}if(name==="htmlFor"){el.setAttribute("for",String(value));return}if(name.startsWith("aria-")||name.startsWith("data-")||name==="role"){el.setAttribute(name,String(value));return}if(name==="autoFocus"){if(value)__autoFocus=el;return}if(["value","checked","selected","disabled","hidden","multiple","required","readOnly"].includes(name)){try{el[name]=value}catch{};return}if(typeof value==="boolean"){if(value)el.setAttribute(name,"");return}try{if(name in el&&name!=="list"&&name!=="form")el[name]=value;else el.setAttribute(name,String(value))}catch{el.setAttribute(name,String(value))}}
function childArray(value){return Array.isArray(value)?flatChildren(value):value===undefined?[]:[value]}
function renderVNode(vnode,path="0",svg=false){if(vnode===null||vnode===undefined||vnode===false||vnode===true)return document.createDocumentFragment();if(typeof vnode==="string"||typeof vnode==="number"||typeof vnode==="bigint")return document.createTextNode(String(vnode));if(Array.isArray(vnode)){const f=document.createDocumentFragment();childArray(vnode).forEach((c,i)=>f.appendChild(renderVNode(c,path+"/"+i,svg)));return f}if(vnode.type===Fragment){const f=document.createDocumentFragment();childArray(vnode.props?.children).forEach((c,i)=>f.appendChild(renderVNode(c,path+"/f"+i,svg)));return f}const marker=vnode.key!=null?"k:"+String(vnode.key):"n";const here=path+"/"+marker;if(typeof vnode.type==="function"){const prevComp=__component,prevIndex=__hookIndex;const compPath=here+":c:"+(vnode.type.name||"anon");__component=compPath;__hookIndex=0;__used.add(compPath);let result;try{result=vnode.type(vnode.props||{})}finally{__component=prevComp;__hookIndex=prevIndex}return renderVNode(result,compPath+"/r",svg)}if(typeof vnode.type!=="string")return document.createDocumentFragment();const tag=vnode.type;const nextSvg=svg||tag==="svg";const el=nextSvg?document.createElementNS("http://www.w3.org/2000/svg",tag):document.createElement(tag);__nodes.set(here,el);if(!nextSvg)el.dataset.vpath=here;for(const [name,value] of Object.entries(vnode.props||{}))applyProp(el,name,value,nextSvg,tag);const ref=vnode.props?.ref;if(ref&&typeof ref==="object")ref.current=el;else if(typeof ref==="function")ref(el);childArray(vnode.props?.children).forEach((c,i)=>{const id=(c&&typeof c==="object"&&!Array.isArray(c)&&c.key!=null)?"k:"+String(c.key):String(i);el.appendChild(renderVNode(c,here+"/"+id,nextSvg))});return el}
function cleanupUnused(){for(const [path,list] of __hooks){if(__used.has(path))continue;for(const slot of list){if(slot?.kind==="effect"&&typeof slot.cleanup==="function")try{slot.cleanup()}catch(e){console.error(e)}}__hooks.delete(path)}}
function runEffects(){for(const item of __pendingEffects){const list=__hooks.get(item.path),slot=list?.[item.index];if(!slot)continue;if(typeof slot.cleanup==="function")try{slot.cleanup()}catch(e){console.error(e)}let cleanup=null;try{cleanup=item.effect()}catch(e){console.error(e)}slot.cleanup=typeof cleanup==="function"?cleanup:null;slot.deps=item.deps}}
function renderRoot(){if(!__root)return;const active=document.activeElement;const activePath=active?.dataset?.vpath||null;let selection=null;if(active&&(active.tagName==="INPUT"||active.tagName==="TEXTAREA")){try{selection=[active.selectionStart,active.selectionEnd,active.selectionDirection]}catch{}}__used=new Set();__pendingEffects=[];__nodes=new Map();__autoFocus=null;const dom=renderVNode(__rootVNode,"root",false);__root.replaceChildren(dom);if(typeof refreshLucideIcons==="function")refreshLucideIcons();cleanupUnused();let focusTarget=activePath?__nodes.get(activePath):null;if(focusTarget){try{focusTarget.focus({preventScroll:true});if(selection&&typeof focusTarget.setSelectionRange==="function"&&selection[0]!=null)focusTarget.setSelectionRange(selection[0],selection[1],selection[2]||"none")}catch{}}else if(__autoFocus){try{__autoFocus.focus()}catch{}}runEffects()}
function createRoot(el){return{render(vnode){__root=el;__rootVNode=vnode;renderRoot()}}}
function safeUuid(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==="x"?r:(r&3|8);return v.toString(16)})}
function uuid(){try{return globalThis.crypto?.randomUUID?globalThis.crypto.randomUUID():safeUuid()}catch{return safeUuid()}}
